@startuml
left to right direction

actor "Usuario" as U

rectangle "Order Management System (v2.0)" {
    usecase "Listar IDs de pedidos" as UC_Listar
    usecase "Buscar detalles de pedido" as UC_Buscar
    usecase "Crear nuevo pedido" as UC_Crear
    usecase "Borrar pedido" as UC_Borrar
    usecase "Editar artículos (Cant/Desc)" as UC_Editar
    
    usecase "Persistir en JSON" as UC_Save
}

U --> UC_Listar
U --> UC_Buscar
U --> UC_Crear
U --> UC_Borrar
U --> UC_Editar

note right of UC_Save
  Esta acción ocurre tras 
  Crear, Borrar o Editar
end note

UC_Crear ..> UC_Save : <<include>>
UC_Borrar ..> UC_Save : <<include>>
UC_Editar ..> UC_Save : <<include>>

@enduml